[workspace]
resolver = "2"
members = [
    "hermit-abi",
    "hermit",
    "benches/alloc",
    "benches/micro",
    "examples/hello_world",
    "examples/httpd",
    "examples/demo",
    "examples/mutex",
    "benches/multithreaded",
    "benches/startup", 
]
exclude = ["target", "kernel"]
