[package]
name = "testudp"
edition = "2021"
version = "0.1.0"

[target.'cfg(target_os = "hermit")'.dependencies]
hermit = { path = "../../hermit", default-features = false }

[features]
default = ["hermit/acpi", "hermit/pci", "hermit/pci-ids", "hermit/udp"]
