name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - test

env:
  GH_TOKEN: ${{ github.token }}
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  kvm:
    name: KVM
    runs-on: [self-hosted]
    steps:
    - name: Install QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-kvm
    - uses: actions/checkout@v4
      with:
         submodules: true
    - uses: mkroening/rust-toolchain-toml@main
    - name: Download loader  
      run: gh release download --repo hermit-os/loader --pattern hermit-loader-x86_64
    - name: Build dev profile
      run: cargo build -Zbuild-std=std,panic_abort --target x86_64-unknown-hermit --package rusty_demo
    - name: Install uhyve
      run: cargo +stable install --locked uhyve
    - name: Check KVM availability
      shell: bash
      run: |
         lscpu
         kvm-ok
    #- name: Test debug version (Uhyve)
    #  run: uhyve --verbose -c 1 target/x86_64-unknown-hermit/debug/rusty_demo
    #  env:
    #    RUST_LOG: debug
    - name: Test debug profile (Qemu)
      run: |
        qemu-system-x86_64 -display none -smp 1 -m 128M -serial stdio \
          -enable-kvm -cpu qemu64,apic,fsgsbase,rdtscp,xsave,xsaveopt,fxsr,rdrand \
          -kernel hermit-loader-x86_64 \
          -initrd target/x86_64-unknown-hermit/debug/rusty_demo
    - name: Build release profile
      run: cargo build -Zbuild-std=std,panic_abort --target x86_64-unknown-hermit --package rusty_demo --release
    #- name: Test release version (Uhyve)
    #  run: uhyve --verbose -c 1 target/x86_64-unknown-hermit/release/rusty_demo
    #  env:
    #    RUST_LOG: debug
    - name: Test release profile (Qemu)
      run: |
        qemu-system-x86_64 -display none -smp 1 -m 128M -serial stdio \
          -enable-kvm -cpu qemu64,apic,fsgsbase,rdtscp,xsave,xsaveopt,fxsr,rdrand \
          -kernel hermit-loader-x86_64 \
          -initrd target/x86_64-unknown-hermit/release/rusty_demo
